import { FC } from "react";
import Head from "next/head";
import NavBar from "../navbar";

export interface LayoutProps {}

const Layout: FC<LayoutProps> = ({ children }) => {
  return (
    <div className="Layout">
      <Head>
        <title>Brad Bieselin</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="" />
      </Head>
      <NavBar />
      {children}
      <style jsx>
        {`
          .Layout {
            height: 100vh;
            padding-left: 10%;
            padding-right: 10%;
            background-color: black;
          }
        `}
      </style>
    </div>
  );
};

export default Layout;
